### PR TITLE
[B] Remove roles page from community/manage

### PR DESCRIPTION
**Pull request by 1aurend**
@jen-castiron I removed roles from the community routes. Should I also delete or move roles.tsx from the community pages folder?

### CODE REVIEW

**Comment by jen-castiron** [comment]
@1aurend Go ahead - it's just a placeholder page at the moment

**Comment by zdavis** [comment]
Please hold on merging this in for a day or two — I'm doing work in the communities section of that pages directory, and want the extra route there for now. Let's let this PR sit until my work is in master, at which point I'll rebase this and accept it.

**Comment by zdavis** [comment]
Ok, feel free to merge this whenever you both feel it's ready! My work is in main. Thanks for holding it back for a bit!

**Comment by jen-castiron** [comment]
@1aurend Looks like this PR is ready, just has a small conflict that needs to be resolved. Let me know if you need assistance!

**Pull request merged**
